In [1]:
import numpy as np
from skimage.io import imread
from skimage.color import rgb2xyz
from matplotlib import pyplot as plt
from scipy.sparse import kron as spkron
from scipy.sparse import eye as speye
from scipy.sparse.linalg import lsqr as splsqr
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import warnings

In [11]:
import numpy as np
a = np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [10,12,13]])

print(np.sum(a, axis=0).shape)

print(a.reshape(-1).reshape(4, 3))

b = a.T

print(b, "\n\n\n")

c = b.T.reshape(2, 2, 3)
print(c)
print(c.shape)


(3,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 13]]
[[ 1  4  7 10]
 [ 2  5  8 12]
 [ 3  6  9 13]] 



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 12 13]]]
(2, 2, 3)


In [12]:
def renderLambertianImage(albedoIm, normalIm, lightVec):
    image = 0

    print(normalIm[0, 0])
    print(lightVec[0, 0])
    print(normalIm[0, 0] * lightVec[0, 0])

    ### YOUR CODE HERE
    image = np.zeros(albedoIm.shape)
    # image = normalIm @ lightVec * albedoIm
    for i in range(albedoIm.shape[0]):
        for j in range(albedoIm.shape[1]):
            image[i, j] = normalIm[i, j] * lightVec[0, 0]

    image = image * albedoIm
    ### END YOUR CODE

    return image

# surface normal
bunny_sn = np.load('data/bunny.npy')

# albedo
h, w, _ = bunny_sn.shape
bunny_albedo = np.ones((h, w))

# source 
light_sources = [np.array([0, 0, 1]).reshape(1,1,3), np.array([0, 1, 0]).reshape(1,1,3), np.array([1, 0, 0]).reshape(1,1,3)]


# Render the images under different light sources
rendered_images = []
for s in light_sources:
    rendered_image = renderLambertianImage(bunny_albedo, bunny_sn, s)
    rendered_images.append(rendered_image)  

[0. 0. 0.]
[0 0 1]
[0. 0. 0.]


ValueError: setting an array element with a sequence.