In [116]:
import numpy as np
import matplotlib.pyplot as plt

In [117]:
X_train = np.array([[0.31, 0.78],
                    [0.33, 0.51],
                    [0.36, 0.73],
                    [0.61, 0.85], 
                    [0.79, 0.76],
                    [0.62, 0.93]])

Y_train = np.array([0, 0, 0, 1, 1, 1])

X_test = np.array([[0.72, 0.38],
                   [0.75, 0.31],
                   [0.39, 0.76], 
                   [0.82, 0.77],
                   [0.76, 0.87],
                   [0.84, 0.44]])

Y_test = np.array([1, 1, 0, 1, 0, 1])

theta_old = np.array([-1, 1.5, 0.5])
alpha = 0.5

In [118]:
'''a'''

# print(theta_old.reshape(3, 1))

X_train = np.concatenate((np.ones((X_train.shape[0], 1)), X_train), axis=1)

sum = np.zeros((3, 1))
for i in range(len(Y_train)):
    sum += ((1/(1+np.exp(-(X_train[i].reshape((1,3)) @ theta_old.reshape(3, 1))))) - Y_train[i]) * X_train[i].reshape((3, 1))
    # print(sum)


theta_new = theta_old.reshape((3, 1)) - 0.1 * sum
print(theta_new)



[[-1.01971897]
 [ 1.53297714]
 [ 0.50704538]]


In [119]:
'''(b)'''
X_test = np.concatenate((np.ones((X_test.shape[0], 1)), X_test), axis=1)


y_test_pred = np.zeros((Y_test.shape[0], 1))

for i in range(X_test.shape[0]):
    # print(1/(1+np.exp(-(X_test[i].reshape((1,3)) @ theta_new.reshape(3, 1)))))
    y_test_pred[i, 0] = 1/(1+np.exp(-(X_test[i].reshape((1,3)) @ theta_new.reshape(3, 1))))

print('calculated probability:\n', y_test_pred)

for i in range(X_test.shape[0]):
    # print(1/(1+np.exp(-(X_test[i].reshape((1,3)) @ theta_new.reshape(3, 1)))))
    y_test_pred[i, 0] = 1 if (1/(1+np.exp(-(X_test[i].reshape((1,3)) @ theta_new.reshape(3, 1)))) >= 0.5) else 0
    y_test_pred

print('classification result:\n', y_test_pred.astype(int))






calculated probability:
 [[0.56873745]
 [0.57131001]
 [0.49087516]
 [0.65197848]
 [0.64255551]
 [0.62036124]]
classification result:
 [[1]
 [1]
 [0]
 [1]
 [1]
 [1]]


C:\Users\16567\AppData\Local\Temp\ipykernel_27580\4184454162.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_test_pred[i, 0] = 1/(1+np.exp(-(X_test[i].reshape((1,3)) @ theta_new.reshape(3, 1))))


In [120]:
5/6

0.8333333333333334